const DECISION_THRESHOLDS = Object.freeze({
  RAIN_THRESHOLD: 70,
  ORDER_DROP_THRESHOLD: 0.5, // 50%
  INCOME_DROP_THRESHOLD: 0.4, // 40%
  INACTIVITY_THRESHOLD_HOURS: 2,
  DEFAULT_COVERAGE: 0.7
});

module.exports = DECISION_THRESHOLDS;
